# Generated by Django 5.0.2 on 2024-02-27 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='', upload_to='uploads/products/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=6)),
                ('rpassword', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField(default=0)),
                ('sprice', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('ram', models.CharField(max_length=20)),
                ('rom', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=20000, null=True)),
                ('f1', models.CharField(default='', max_length=100)),
                ('f2', models.CharField(default='', max_length=100)),
                ('f3', models.CharField(default='', max_length=100)),
                ('f4', models.CharField(default='', max_length=100)),
                ('f5', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='uploads/products/')),
                ('image1', models.ImageField(default='', upload_to='uploads/products/')),
                ('image2', models.ImageField(default='', upload_to='uploads/products/')),
                ('image3', models.ImageField(default='', upload_to='uploads/products/')),
                ('quantity', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mobile.brand')),
            ],
        ),
    ]
