# Generated by Django 5.0.2 on 2024-02-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oquantity',
            field=models.IntegerField(default=1),
        ),
    ]
